version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - run: 
          name: display glob
          command: |   
              TESTFILES=$(circleci tests glob "**/*.m")
              #TESTFILES="testAbsValue_basic testAbsValue_parameterized testCubeRoot_basic testCubeRoot_parameterized" 
              SPLIT_TESTFILES=$(echo "$TESTFILES" | circleci tests split)
              echo "$SPLIT_TESTFILES"
                   
workflows:
  glob_learning:
    jobs:
      - build