version: '2.1'
orbs:
  matlab: mathworks/matlab@1
  
jobs:
     
  build_script:
    machine:
      image: default
      
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: pwd
          
          
          
workflows:
  build:
    jobs:
      - build_script
