version: 2.1              
orbs:
  matlab: mathworks/matlab@1 
jobs:
  build:
    machine: true 
    resource_class: vandit/lease
    parallelism: 1  
    steps: 
      - run:
          name: Run MATLAB Test with CircleCI Test Splitting
          shell: powershell.exe 
          command: |
            cd L:\E\matlab\test\toolbox\simulink\variants\var-general
            sb -m -batch -m sim_test
            

         
workflows:   
  Simulink_Test: 
    jobs:
      - build    
       