version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - matlab/install
      - run: 
          name: Run MATLAB test with test splitting
          command: |
              cd tests/
              TESTFILES=$(circleci tests glob "**"| circleci tests split --split-by=timings)
              echo "$TESTFILES"      
              FORMATTED_TESTFILES=$(echo "$TESTFILES" | awk '{printf "\x27%s\x27,", $0}' | sed 's/,$//')
              echo "{$FORMATTED_TESTFILES}"
              matlab-batch "addpath('tests'); runTestsAndGenerateReports({$FORMATTED_TESTFILES})"

      - store_test_results:
          path: tests/results.xml              


          
workflows:
  changing_directory:
    jobs:
      - build
