version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/class_window
    parallelism: 2  
    steps:
      - matlab/install:
          products: Parallel_Computing_Toolbox
      - run:
          name: "Moving to Directory"
          command: |
            cd F:\sbs\37\vandita.Btestframework.j2547610\matlab\test\toolbox\matlab\testframework\unittest\core\matlab\unittest
            ls
      - matlab/run-tests:
          use-parallel: true

 
            
                   
workflows:
  self_hosted_runner_network_repo:
    jobs:
      - build