version: '2.1'      
orbs:
  matlab: mathworks/matlab@1 
jobs:
  build:
    machine: true 
    resource_class: vandit/lease
    parallelism: 2
    steps: 
      - run: 
          name: Find MATLAB Installation Path 
          command: | 
            echo "Finding MATLAB installation path..."
            which matlab || echo "MATLAB not found in PATH"
            echo "Finding CircleCI installation path..." 
            which circleci
      - run:
          name: Execute CircleCI Tests Glob Command in MATLAB
          command: |
             matlab -batch "runCircleCITests"              

                   
workflows:
  Testing execution: 
    jobs:
      - build    