version: 2.1                      
orbs:  
  matlab: mathworks/matlab@1    
jobs:   
  build:
    machine: true  
    resource_class: vandit/lease 
    parallelism: 2  
    steps: 
      - run:
          command: |
              matlab -batch "my_genscript"
 


workflows:   
  select_if: 
    jobs:
      - build             
             

 