version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - matlab/install
      - run: 
          name: Run MATLAB test with test splitting
          command: |
              cd tests/
              TESTFILES=$(circleci tests glob "**"| circleci tests split)
              echo "$TESTFILES"      
              FORMATTED_TESTFILES=$(echo "$TESTFILES" | awk '{printf "\x27%s\x27,", $0}' | sed 's/,$//')
              cd ..
              matlab-batch "runTestsAndGenerateReports({$FORMATTED_TESTFILES})"
            

          
workflows:
  SPLIT_BY_FILE_NAME:
    jobs:
      - build
