version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - run:
          command: |
            TESTFILES="TestAbsValue_basic.m TestAbsValue_parameterized.m TestCubeRoot_basic.m TestCubeRoot_parameterized.m" 
            echo $TESTFILES | tr ' ' '\n' > circleci_test_files1.txt
            TESTFILES=$(circleci tests split --split-by=timings circleci_test_files1.txt)
            echo $TESTFILES
            
                   
workflows:
  storing_text_file:
    jobs:
      - build