version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - run:
          command: |
            TESTFILES="TestAbsValue_basic.m TestAbsValue_parameterized.m TestCubeRoot_basic.m TestCubeRoot_parameterized.m" 
            TESTFILES=echo $TESTFILES | tr ' ' '\n' | circleci tests split 
            echo $TESTFILES
            
                   
workflows:
  storing_variable:
    jobs:
      - build