version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:current  # Use the appropriate machine image for your project

    steps:
      - checkout

      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-venv python3-pip

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install unittest-xml-reporting

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python test_example.py

      - store_artifacts:
          path: results.xml
          destination: test-results

workflows:
  version: 2
  python_test:
    jobs:
      - test