version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  run-matlab-tests:    
    machine:
      image: ubuntu-2204:current
    parallelism: 4
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          select-by-name: $(circleci tests glob "tests/**/*.m" | circleci tests split | awk -F'[\\\\/.]' '{print $(NF-1) "/*"}')
workflows:
  test:
    jobs:
      - run-matlab-tests