version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - matlab/install:
          products: Parallel_Computing_Toolbox
      - matlab/run-tests:
          use-parallel: true

 
            
                   
workflows:
  use_Parallel:
    jobs:
      - build