version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - run:
          command: |
            TESTFILES="test1.py test2.py test3.py" # replace with your list of test files
            echo $TESTFILES | tr ' ' '\n' > circleci_test_files.txt
            TESTFILES=$(circleci tests split --split-by=timings circleci_test_files.txt)
            echo $TESTFILES
            # run your tests with the split files
                   
workflows:
  without_glob:
    jobs:
      - build