version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2 
    steps:
      - checkout
      - matlab/install:
          release: R2023a

      - run:  
          name: circleci test split
          command: |
              TESTFILES=$(circleci tests glob "**/*.m")
              echo "$TESTFILES"
              SPLIT_TESTFILES=$(echo "$TESTFILES" | circleci tests split)
              echo "$SPLIT_TESTFILES"    
              FORMATTED_TESTFILES=$(echo "$SPLIT_TESTFILES" | awk '{printf "\x27%s\x27,", $0}' | sed 's/,$//')
              echo "{$FORMATTED_TESTFILES}"                        
              matlab-batch "runTestsAndGenerateReports(${FORMATTED_TESTFILES})"            


          
workflows:
  circleci_test_split_command:
    jobs:
      - build