version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - matlab/install
      - run: 
          name: Run MATLAB test with test splitting
          command: |
              cd tests/
              TESTFILES=$(circleci tests glob "**/*.m" | xargs -n1 basename | sed 's/\.m$//')
              SPLIT_TESTFILES=$(echo "$TESTFILES" | circleci tests split)
              echo "$SPLIT_TESTFILES"
              FORMATTED_TESTFILES=$(echo "$SPLIT_TESTFILES" | awk '{printf "\x27%s\x27,", $0}' | sed 's/,$//')
              echo "{$FORMATTED_TESTFILES}"
              cd ..
              matlab-batch "runTestsAndGenerateReports({$FORMATTED_TESTFILES})"           
          
workflows:
  SPLIT_BY_FILE_NAME :
    jobs:
      - build
