version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/kapilg-vdi
    steps: 
      - run:
          command: 
              matlab -batch ver
 
            
                    
workflows:  
  vdi_tmpdir_location:
    jobs: 
      - build 