version: '2.1'            
orbs:
  matlab: mathworks/matlab@1 
jobs:
  build:
    machine: true 
    resource_class: vandit/lease
    parallelism: 1
    steps: 
      - run:
          name: Trying POC 
          command: |
             matlab -batch "poc"             

                    
workflows:   
  POC_TRY: 
    jobs:
      - build    
       