version: 2.1
orbs: 
  matlab: mathworks/matlab@1 
jobs:
  test:
    machine:
      image: ubuntu-2004:current 
    parallelism: 2
    steps:
      - checkout  

      - run:
          name: Debug Test Files
          command: |
              output=$(circleci tests glob 'tests/**/*.m' | circleci tests split | awk -F'[/.]' '{print $(NF-1) "/*"}')
              echo "Test files found:"
              selectByName=$(echo "$output" | awk '{for(i=1;i<=NF;i++) printf "\x27%s\x27%s", $i, (i==NF ? "" : ", ")}')
              echo "$selectByName"
              
workflows:
  version: 2
  try:
    jobs:
      - test