version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/lease
    steps: 
     
      - run:
          command: |
                  cd \\mathworks\devel\jobarchive\BR2023bd\latest_pass\matlab\test\toolbox\matlab\testframework\unittest\core\matlab\unittest       
          shell: powershell.exe -noprofile -noninteractive -command          

      - matlab/run-tests       
  
            
                     
workflows:  
  actual_test_cases:
    jobs: 
      - build  