version: 2.1                 
orbs:
  matlab: mathworks/matlab@1  
jobs:
  build:
    machine: true 
    resource_class: vandit/lease
    parallelism: 1  
    steps: 
      - matlab/install:
          release: R2023b

      - matlab/run-tests: 
          select-by-folder: tests
          test-results-junit: tests/results.xml
          test-results-pdf: tests/results.pdf

      - store_artifacts:
          path: tests/results.xml
          destination: results.xml

      - store_artifacts:
          path: tests/results.pdf
          destination: results.pdf

workflows:   
  pdf_generation: 
    jobs:
      - build             
            

 