version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2 
    steps:
      - checkout
      - matlab/install:
          release: R2023a

      - run:  
          name: Run MATLAB test with test splitting
          command: |
              cd tests/
              TESTFILES=$(circleci tests glob "**/*.m" | xargs -n1 basename | sed 's/\.m$//')
              SPLIT_TESTFILES=$(echo "$TESTFILES" | circleci tests split --split-by=timings)
              matlab-batch "runTestsAndGenerateReports()"

      - store_test_results:
          path: tests-results             


          
workflows:
  custom_function:
    jobs:
      - build