version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/lease
    steps: 
      - run:
          name: Access a network path with PowerShell
          command: |
            Set-Location -Path 'C:\Users\vandita\Downloads'
          shell: powershell.exe -noprofile -noninteractive -command               
                     
workflows:  
  actual_test_cases:
    jobs: 
      - build  