version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - matlab/install
      - run: 
          name: Run MATLAB test with test splitting
          command: |
              TESTFILES=$(circleci tests glob "tests/*.m" | circleci tests split --split-by=timings --timings-type=classname | sed 's|tests/||')
              echo "$TESTFILES"
              FORMATTED_TESTFILES=$(echo "$TESTFILES" | awk '{printf "\x27%s\x27,", $0}' | sed 's/,$//')
              echo "{$FORMATTED_TESTFILES}"
              matlab-batch "addpath('tests'); runTestsAndGenerateReports({$FORMATTED_TESTFILES})" 
          
      - store_test_results:
          path: test-results
workflows:
  running_matlab_batch_with_param:
    jobs:
      - build
