version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/vdi
    steps: 
      - run:
          command: |
            $tmpdir = New-TemporaryFile | ForEach-Object { $_.DirectoryName }
            Remove-Item $tmpdir -Force # This is just to get the directory path; we delete the temp file immediately.
            Write-Host "Temporary directory is created at: $tmpdir"
            
 

 
            
                   
workflows:
  vdi_tmpdir_location:
    jobs:
      - build