version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/class_window 
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: "disp('Hello, World!')"
workflows:
  self_hosted_open_matlab:
    jobs:
      - build