version: 2.1                 
orbs:
  matlab: mathworks/matlab@1  
jobs:
  build:
    machine: true 
    resource_class: vandit/lease
    parallelism: 1  
    steps: 
      - matlab/run-tests: 
          select-by-folder: tests
          test-results-junit: test/results.xml
          test-results-pdf: test/results.pdf
      - run:
          name: Run MATLAB Test with PDF generation
          command: |
            echo "Printing pdf report, junit results and html test results"  
            
            

 