version: '2.1'
orbs:
  matlab: mathworks/matlab@0
  
jobs:
  build_test:
    machine:
      image: ubuntu-2004:current 
    parallelism: 2 
    steps:
      - checkout

      - matlab/install

      - run:
          name: Run MATLAB tests with Test Splitting
          command: |
                  TESTFILES=$(circleci tests glob "tests/*.m" | circleci tests split --split-by=timings)
                  echo "$TESTFILES"
                  FORMATTED_TESTFILES="'$(echo $TESTFILES | sed "s/ /', '/g")'"
                  matlab -batch "addpath('tests'); import matlab.unittest.TestRunner; import matlab.unittest.plugins.XMLPlugin; import matlab.unittest.plugins.ToFile; suite = testsuite({$FORMATTED_TESTFILES}, 'IncludeSubfolders', true); runner = TestRunner.withTextOutput; xmlFile = 'testResults/results.xml'; runner.addPlugin(XMLPlugin.producingJUnitFormat(ToFile(xmlFile))); results = runner.run(suite);"

      - store_test_results:
          path: testResults/results.xml      
          
          
          
workflows:
  build:
    jobs:
      - build_test
      
