version: 2.1
orbs: 
  matlab: mathworks/matlab@1 
jobs:
  test:
    machine:
      image: ubuntu-2004:current 
    parallelism: 2
    steps:
      - checkout  

      - run:
          name: Debug Test Files
          command: |
            PARAM_SELECT_BY_NAME=$('test1' 'test2' 'test3' 'test4' | circleci tests split | awk -F'[/.]' '{print "\047" $(NF-1) "\047"}' | paste -sd, -)
            selectByName=$(eval echo "$PARAM_SELECT_BY_NAME" | awk '{
                for(i=1; i<=NF; i++) {
                    gsub(/\047/, "\047\047", $i);  
                    printf "\047%s\047%s", $i, (i==NF ? "" : ", "); 
                }
            }')
            selectByName="{$selectByName}"
            echo "$selectByName"
              
workflows:
  version: 2
  try:
    jobs:
      - test