version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/lease
    steps: 
      - run:
          command: 
              matlab -batch ver
              
      - matlab/run-tests       
  
            
                    
workflows:  
  lease:
    jobs: 
      - build  