version: '2.1'              
orbs:
  matlab: mathworks/matlab@1 
jobs:
  build:
    machine: true 
    resource_class: vandit/lease
    parallelism: 2 
    steps: 
      - run:
          name: Run MATLAB Test with CircleCI Test Splitting
          command: |
            cd L:\C\matlab\test\toolbox\simulink\variants\var-general
            sb
            echo "present directory $pwd"
                    
workflows:   
  POC_TRY_2: 
    jobs:
      - build    
       