version: '2.1'
orbs:
  matlab: mathworks/matlab@1
  
jobs:
  build_test:
    machine:
      image: ubuntu-2004:current  
    environment:
      MATHWORKS_TOKEN: gv8qAx4MC2cqxQLN3CJ0QBWgDFAUp9Ht/lf4DR2m0TyIpbYKRDOSOYi0f76X23BKPpWQLjnl4I3FGAHampAz8xaM9FHEAW4QPj37LnhMUscKmnJf2XS0p6hy4zTbM2c1UznG4/lX0xCvxx1Vvte6qg==
      MATHWORKS_ACCOUNT: kapilg@mathworks.com

    steps:
      - checkout
      - matlab/install
      - run:
          name: Run MATLAB tests with Test Splitting
          command: |
              echo $MATHWORKS_TOKEN 
              
              matlab-batch pwd
          
          
workflows:
  build:
    jobs:
      - build_test
      
