version: '2.1'
orbs:
  matlab: mathworks/matlab@1
  
jobs:
     
  build_script:
    machine:
      image: ubuntu-2004:current
      
    steps:
      - checkout
      - matlab/install:
          release: R2022b
      - matlab/run-command:
          command: myscript
          
          
workflows:
  build:
    jobs:
      - build_script
