version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/kapilg-vdi
    steps: 
      - run:
          command: |
            tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'run-tests')
            echo "Temporary directory is created at: $tmpdir"
            curl -sfLo "${tmpdir}/scriptgen.zip" https://ssd.mathworks.com/supportfiles/ci/matlab-script-generator/v0/matlab-script-generator.zip          
            unzip -qod "${tmpdir}/scriptgen" "${tmpdir}/scriptgen.zip"

 
            
                   
workflows:
  vdi_tmpdir_location:
    jobs:
      - build