version: 2.1        
orbs:
  matlab: mathworks/matlab@1 
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:   
      - checkout
      - run:
          command: cd tests 
      - matlab/install
      - matlab/run-tests:
          test-results-junit: results.xml

                     
workflows:   
  run-tests: 
    jobs:
      - build    
       

