version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/class_window 
    parallelism: 4 
    steps:
      - checkout
      - run:  
          name: Run MATLAB test with test splitting
          command: |
              cd tests/
              TESTFILES=$(circleci tests glob "**/*.m" | xargs -n1 basename | sed 's/\.m$//')
              SPLIT_TESTFILES=$(echo "$TESTFILES" | circleci tests split --split-by=timings --timings-type=classname)
              echo "$SPLIT_TESTFILES"
              FORMATTED_TESTFILES=$(echo "$SPLIT_TESTFILES" | awk '{printf "\x27%s\x27,", $0}' | sed 's/,$//')
              echo "{$FORMATTED_TESTFILES}"
              cd ..
              matlab -batch "runTestsAndGenerateReports({$FORMATTED_TESTFILES})"

      - store_test_results:
          path: tests/results.xml              


          
workflows:
  parallel_3_cloud_my_repo:
    jobs:
      - build
