version: 2.1
orbs:
  matlab: mathworks/matlab@1
  win: circleci/windows@5.0

jobs:
  test-linux:
    machine:
      image: ubuntu-2004:current
    parallelism: 2
    steps:
      - checkout
      - run:
          command: |
            x=$(circleci tests glob 'tests/**/*.m' | circleci tests split | awk -F'[\\/]' '{print $NF "/*"}')
            echo "Displaying x"
            echo "$x"

  test-macos:
    macos:
      xcode: "13.2.1" # You can choose the appropriate Xcode version
    steps:
      - checkout
      - run:
          command: |
            x=$(circleci tests glob 'tests/**/*.m' | circleci tests split | awk -F'[\\/]' '{print $NF "/*"}')
            echo "Displaying x"
            echo "$x"

  test-windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
             x=$(circleci tests glob 'tests/**/*.m' | circleci tests split | awk -F'[\\/]' '{print $NF "/*"}')
             echo "Displaying x"
             echo $x

workflows:
  version: 2
  try:
    jobs:
      - test-linux
      - test-macos
      - test-windows