version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - matlab/install:
          products: Parallel_Computing_Toolbox
      - matlab/run-tests:
          use-parallel: true
                   
workflows:
  cloudrunner_my_repo_useParallel:
    jobs:
      - build