version: 2.1
orbs: 
  matlab: mathworks/matlab@1 
jobs:
  test:
    machine:
      image: ubuntu-2004:current 
    parallelism: 2
    steps:
      - checkout  
      - run:
          command: |
                    x= $(circleci tests glob 'tests/**/*.m' | circleci tests split | awk -F'[\\/]' '{print $(NF-1) "/*"}'
                    echo "Displaying x"
                    echo x
              
workflows:
  version: 2
  try:
    jobs:
      - test