version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/vdi
    steps: 
      - checkout   
      - matlab/run-tests
                           
workflows:
  self_hosted_runner_ls:
    jobs:
      - build  