version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:current  # Use the appropriate machine image for your project
    parallelism: 2
    steps:
      - checkout

      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-venv python3-pip

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install unittest-xml-reporting
          
      - run:
          name: Split Test Files
          command: |
            TEST_FILES=$(circleci tests glob "tests_python/**/*.py" | circleci tests split --split-by=timings)
            echo $TEST_FILES
            echo $TEST_FILES > split_test_files.txt

      - run:
          name: Run Split Tests
          command: |
            . venv/bin/activate
            TEST_FILES=$(cat split_test_files.txt)
            python run_split_tests.py $TEST_FILES
            
      - store_test_results:
          path: test-results      

      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  version: 2
  splitting_python_test_full_path:
    jobs:
      - test