version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - matlab/install:
          products: Parallel_Computing_Toolbox
      - run:
          name: Show MATLAB Installation Path
          command: |
                  which MATLAB
                   
workflows:
  cloudrunner_install_path:
    jobs:
      - build