version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/r_s
    steps: 
      - checkout   
      - run:
            command: >
              downloadAndRun() {
                  url=$1
                  shift
                  if [[ -x $(command -v sudo) ]]; then
                  curl -sfL $url | sudo -E bash -s -- "$@"
                  else
                  curl -sfL $url | bash -s -- "$@"
                  fi
              }


              tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'run-tests')


              # install run-matlab-command

              downloadAndRun
              https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2/install.sh
              "${tmpdir}/bin"


              # download script generator

              curl -sfLo "${tmpdir}/scriptgen.zip"
              https://ssd.mathworks.com/supportfiles/ci/matlab-script-generator/v0/matlab-script-generator.zip

              unzip -qod "${tmpdir}/scriptgen" "${tmpdir}/scriptgen.zip"

              echo "please print the present working directory"
              echo $tmpdir




                           
workflows:
  self_hosted_runner_matlab_run_tests:
    jobs:
      - build     