version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2  
    steps:
      - checkout
      - matlab/install
      - run: 
          name: Run MATLAB test with test splitting
          command: |
              cd tests/
              TESTFILES=$(circleci tests glob "**")
              echo "$TESTFILES"      
          
workflows:
  trial1:
    jobs:
      - build
