version: '2.1'         
orbs:
  matlab: mathworks/matlab@1 
jobs:
  build:
    machine: true 
    resource_class: vandit/lease
    parallelism: 1
    steps: 
      - run: 
          name: Find MATLAB Installation Path 
          command: | 
            echo "Finding MATLAB installation path..."
            which matlab || echo "MATLAB not found in PATH"
            echo "Finding CircleCI installation path..."  
            which circleci
      - run:
          name: Execute CircleCI Tests Glob Command in MATLAB
          command: |
             cd tests
             circleci tests glob "**/*.m" | circleci tests run --command "xargs matlab -batch runtests" --split-by=timings              

                   
workflows:  
  circleci test run: 
    jobs:
      - build    