version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/vdi
    steps: 
      - matlab/run-tests
 

 
            
                   
workflows:
  vdi:
    jobs:
      - build