version: 2.1
orbs: 
  matlab: mathworks/matlab@1 
jobs:
  test:
    machine:
      image: ubuntu-2004:current 
    parallelism: 2
    steps:
      - checkout

      - matlab/install:
          products: Simulink Simulink_Test Simulink_Coverage Parallel_Computing_Toolbox
          no-output-timeout: 30m
          
      - matlab/run-tests:
          select-by-folder: 'tests'
          test-results-junit: 'results.xml' 
      
      - store_test_results:
           path: results.xml

      - store_artifacts:
          path: results.xml
          destination: test-results/results.xml     

workflows:
  version: 2
  Genscript:
    jobs:
      - test