version: '2.1'
orbs:
  matlab: mathworks/matlab@1
  
jobs:
  build_run:
    machine:
      image: ubuntu-2204:2022.07.1
      
    steps:
      - checkout
      - matlab/install
      - matlab/run-build:  

  build_script:
    machine:
      image: ubuntu-2004:current
      
    steps:
      - checkout
      - matlab/install:
          release: R2022b
      - matlab/run-command:
          command: myscript
          
          
workflows:
  build:
    jobs:
      - build_run
      - build_script
      
