version: '2.1'
orbs:
  matlab: mathworks/matlab@0
  
jobs:
  build_test:
    machine:
      image: ubuntu-2004:current 
    parallelism: 2 
    steps:
      - checkout

      - matlab/install

      - run:
          name: Run MATLAB tests with Test Splitting
          command: |
              TESTFILES=$(circleci tests glob "tests/*.m" | circleci tests split --split-by=timings)
              echo "$TESTFILES"
              FORMATTED_TESTFILES="'$(echo $TESTFILES | sed "s/ /', '/g")'"
              matlab -batch "addpath('tests'); results = runtests({$FORMATTED_TESTFILES}, 'IncludeSubfolders', true);
              import matlab.unittest.TestRunner;
              import matlab.unittest.plugins.XMLPlugin;
              runner = TestRunner.withTextOutput;
              xmlFile = 'testResults/results.xml';
              runner.addPlugin(XMLPlugin.producingJUnitFormat(xmlFile));
              runner.run(results);"

      - store_test_results:
          path: testResults/results.xml      
          
          
          
workflows:
  build:
    jobs:
      - build_test
      
