version: '2.1'
orbs:
  matlab: mathworks/matlab@1
  
jobs:
  build_test:
    machine:
      image: ubuntu-2004:current  
    environment:
      MATHWORKS_TOKEN: $MATHWORKS_TOKEN
      MATHWORKS_ACCOUNT: $MATHWORKS_ACCOUNT

    steps:
      - checkout
      - matlab/install
      - run:
          name: Run MATLAB tests with Test Splitting
          command: |
              matlab-batch pwd
          
          
workflows:
  build:
    jobs:
      - build_test
      
