version: 2.1                
orbs:
  matlab: mathworks/matlab@1 
jobs:
  build:
    machine: 
      image: ubuntu-2004:current

    parallelism: 1  
    steps: 
      - checkout
      - matlab/install
      - matlab/run-tests:
          select-by-folder: tests
          test-results-junit: test/results.xml
          test-results-pdf: tests/results.pdf
      - run:
          name: Run MATLAB Test with PDF generation
          command: |
            echo "Printing pdf report, junit results and html test results"  
            
            

 