version: '2.1'   
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true 
    resource_class: vandit/lease
    parallelism: 2  
    steps:
      - run:
          name: Print the Name of the Machine
          command: |
            echo "The name of the machine is:"
            hostname      
      - run:  
          name: Run MATLAB test with test splitting 
          command: | 
              cd "C:\Users\vandita\OneDrive - MathWorks\Desktop\actual_test"
              ls

         
      
   
 
           
workflows:
  shared_network:
    jobs:
      - build

  
 