version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2 
    steps:
      - checkout
      - matlab/install:
          release: R2023a

      - run:  
          name: circleci test run
          command: |
              cd tests/
              TESTFILES=$(circleci tests glob "**/*.m" | xargs -n1 basename | sed 's/\.m$//')
              echo "$TESTFILES"
              echo "END OF TESTFILES"
              echo "$SPLIT_TESTFILES"
              FORMATTED_TESTFILES=$(echo "$TESTFILES" | awk '{printf "\x27%s\x27,", $0}' | sed 's/,$//')
              echo "STARTING ....................."
              echo "{$FORMATTED_TESTFILES}"
              echo "ENDING ................."
              cd ..
              circleci test run --command "matlab-batch 'runTestsAndGenerateReports({$FORMATTED_TESTFILES})'"        


          
workflows:
  circleci_test_run_command:
    jobs:
      - build