version: '2.1'
orbs:
  matlab: mathworks/matlab@0
  
jobs:
  build_test:
    machine:
      image: ubuntu-2004:current 
    parallelism: 2 
    steps:
      - checkout
      - matlab/install
      - run:
          name: Run MATLAB tests with Test Splitting
          command: |
              TESTFILES=$(circleci tests glob "tests/*.m" | circleci tests split)
              FORMATTED_TESTFILES="'$(echo $TESTFILES | sed "s/ /', '/g")'"
              matlab -batch "addpath('tests'); testResults = runtests({$FORMATTED_TESTFILES}, 'IncludeSubfolders', true);"
          
          
          
workflows:
  build:
    jobs:
      - build_test
      