version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - matlab/install:
          products: Parallel_Computing_Toolbox
      - run:
          name: Find MATLAB Installation Path
          command: |
            echo "Finding MATLAB installation path..."
            which matlab || echo "MATLAB not found in PATH"
            echo "Finding CircleCI installation path..."
            which circleci
      - run:
          name: Execute CircleCI Tests Command in MATLAB
          command: |
            cd tests/
            matlab -batch "system('TESTFILES=$(circleci tests glob \"**/*.m\" | xargs -n1 basename | sed ''s/\\.m$//''); echo $TESTFILES');"
                   
workflows:
  Execute CircleCI Tests Command in MATLAB:
    jobs:
      - build