version: 2.1
orbs: 
  matlab: mathworks/matlab@1 
jobs:
  test:
    machine:
      image: ubuntu-2004:current  # Use the appropriate machine image for your project
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Split Test Files
          command: |
              PARAM_SELECT_BY_FILES="\$(circleci tests glob \"tests/**/*.m\" | circleci tests split)"
              echo "Stored command in PARAM_SELECT_BY_FILES: $PARAM_SELECT_BY_FILES"
              TESTFILES=$(eval echo "$PARAM_SELECT_BY_FILES")
              echo "Evaluated output in TESTFILES: $TESTFILES"


workflows:
  version: 2
  splitting_by_filename:
    jobs:
      - test