version: 2.1                
orbs:
  matlab: mathworks/matlab@1 
jobs:
  build:
    machine: 
      image: ubuntu-2004:current
    parallelism: 1  
    steps: 
      - matlab/run-tests:
          select-by-folder: \tests
          test-results-pdf: \tests
          test-results-junit: \tests
          test-results-html: \tests

      - run:
          name: Run MATLAB Test with PDF generation
          shell: powershell.exe 
          command: |
            echo "Printing pdf report, junit results and html test results"  
            
            

         
workflows:   
  pdf_generation: 
    jobs:
      - build    
       