version: '2.1'
orbs:
  matlab: mathworks/matlab@1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    parallelism: 2 

    environment:
      MLM_LICENSE_TOKEN: vandita@mathworks.com|sample_token|AAARVVEZvhqxL9+Ll4ful+YZMoOuIU0eJqwF8jMo3y5CIqQkteNecayfQ7RsmheqJb+z/on9UfS/oHO94vJ/+S0nPQ4mgzA481iDJacYrvcfdT5vjAqMFTZJyxYLsfROl2+iNx7r/M0floCviegWrjYL8p4qFRav2diUjvRo7w9HWdRJzDt6ZwA

    steps:
      - checkout
      - matlab/install
      - run: 
          name: Run MATLAB test with test splitting
          command: |
              TESTFILES=$(circleci tests glob "tests/*.m" | circleci tests split)  
              echo "$TESTFILES"
              FORMATTED_TESTFILES="'$(echo $TESTFILES | sed "s/ /', '/g")'"
              matlab -batch "addpath('tests'); runTestsAndGenerateReports" 
          
      - store_test_results:
          path: test-results
workflows:
  add_env:
    jobs:
      - build
