version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - matlab/install:
          products: Parallel_Computing_Toolbox
      - run:
          name: Find MATLAB Installation Path
          command: |
            echo "Finding MATLAB installation path..."
            which matlab || echo "MATLAB not found in PATH"
            echo "Finding CircleCI installation path..."
            which circleci
      - run:
          name: Execute CircleCI Version Command in MATLAB
          command: |
            matlab -batch "system('circleci version');"
                   
workflows:
  Execute CircleCI Version Command in MATLAB:
    jobs:
      - build