version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine:
      image: ubuntu-2004:current 
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: tests/results.xml
      - run:
          name: Display Test Results
          command: cat tests/results.xml      
      - store_test_results:
          path: tests/results.xml              


          
workflows:
  matlab_task_disp_xml :
    jobs:
      - build
