version: '2.1'
orbs:
  matlab: mathworks/matlab@1
jobs:
  build:
    machine: true
    resource_class: vandit/class_window 
    steps:
      - checkout
      - run:
         command: 
              Write-Output "Current Working Directory:"
              pwd
                       
              Write-Output "Listing all files and directories:"
              Get-ChildItem -Force
workflows:
  self_hosted:
    jobs:
      - build